## Numerical Linear Algebra
## Homework_1 Exercise_5

### Libraries importation

In [1]:
import numpy
import scipy . linalg

from scipy.sparse import diags
import numpy as np

# Resoltion through the normal equation 
### Vandermonde matrix generation

In [5]:
X = np.linspace(-1, 1, 10)
A = np.vander(X, 6, True)
print(A)
Z = np.dot(A.transpose(), A)
print(Z)

[[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00 -1.00000000e+00
   1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00 -7.77777778e-01  6.04938272e-01 -4.70507545e-01
   3.65950312e-01 -2.84628021e-01]
 [ 1.00000000e+00 -5.55555556e-01  3.08641975e-01 -1.71467764e-01
   9.52598689e-02 -5.29221494e-02]
 [ 1.00000000e+00 -3.33333333e-01  1.11111111e-01 -3.70370370e-02
   1.23456790e-02 -4.11522634e-03]
 [ 1.00000000e+00 -1.11111111e-01  1.23456790e-02 -1.37174211e-03
   1.52415790e-04 -1.69350878e-05]
 [ 1.00000000e+00  1.11111111e-01  1.23456790e-02  1.37174211e-03
   1.52415790e-04  1.69350878e-05]
 [ 1.00000000e+00  3.33333333e-01  1.11111111e-01  3.70370370e-02
   1.23456790e-02  4.11522634e-03]
 [ 1.00000000e+00  5.55555556e-01  3.08641975e-01  1.71467764e-01
   9.52598689e-02  5.29221494e-02]
 [ 1.00000000e+00  7.77777778e-01  6.04938272e-01  4.70507545e-01
   3.65950312e-01  2.84628021e-01]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.0000

### Vector second member

In [7]:
Y = (np.linspace(-1, 1, 10))**2
b = np.dot(A.transpose(), Y)
b

array([ 4.07407407e+00, -4.44089210e-16,  2.94741655e+00, -4.44089210e-16,
        2.50430433e+00, -2.22044605e-16])

### Resolution

In [8]:
scipy.linalg.solve(Z, b)

array([-2.69743076e-16, -9.87868997e-31,  1.00000000e+00,  4.07730542e-30,
       -2.44211006e-45, -3.16558355e-30])

# Resolution through the QR factorization
### Vandermonde matrix 

In [9]:
A

array([[ 1.00000000e+00, -1.00000000e+00,  1.00000000e+00,
        -1.00000000e+00,  1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00, -7.77777778e-01,  6.04938272e-01,
        -4.70507545e-01,  3.65950312e-01, -2.84628021e-01],
       [ 1.00000000e+00, -5.55555556e-01,  3.08641975e-01,
        -1.71467764e-01,  9.52598689e-02, -5.29221494e-02],
       [ 1.00000000e+00, -3.33333333e-01,  1.11111111e-01,
        -3.70370370e-02,  1.23456790e-02, -4.11522634e-03],
       [ 1.00000000e+00, -1.11111111e-01,  1.23456790e-02,
        -1.37174211e-03,  1.52415790e-04, -1.69350878e-05],
       [ 1.00000000e+00,  1.11111111e-01,  1.23456790e-02,
         1.37174211e-03,  1.52415790e-04,  1.69350878e-05],
       [ 1.00000000e+00,  3.33333333e-01,  1.11111111e-01,
         3.70370370e-02,  1.23456790e-02,  4.11522634e-03],
       [ 1.00000000e+00,  5.55555556e-01,  3.08641975e-01,
         1.71467764e-01,  9.52598689e-02,  5.29221494e-02],
       [ 1.00000000e+00,  7.77777778e-01,  6.049

### QR factorization

In [10]:
Q, R = np.linalg.qr(A)
Q

array([[-0.31622777, -0.49543369,  0.52223297,  0.45342519, -0.33658092,
         0.21483446],
       [-0.31622777, -0.38533732,  0.17407766, -0.15114173,  0.41137668,
        -0.50128041],
       [-0.31622777, -0.27524094, -0.08703883, -0.37785433,  0.31788198,
         0.03580574],
       [-0.31622777, -0.16514456, -0.26111648, -0.33467098, -0.05609682,
         0.39386318],
       [-0.31622777, -0.05504819, -0.34815531, -0.12955006, -0.33658092,
         0.21483446],
       [-0.31622777,  0.05504819, -0.34815531,  0.12955006, -0.33658092,
        -0.21483446],
       [-0.31622777,  0.16514456, -0.26111648,  0.33467098, -0.05609682,
        -0.39386318],
       [-0.31622777,  0.27524094, -0.08703883,  0.37785433,  0.31788198,
        -0.03580574],
       [-0.31622777,  0.38533732,  0.17407766,  0.15114173,  0.41137668,
         0.50128041],
       [-0.31622777,  0.49543369,  0.52223297, -0.45342519, -0.33658092,
        -0.21483446]])

In [15]:
Y

array([1.        , 0.60493827, 0.30864198, 0.11111111, 0.01234568,
       0.01234568, 0.11111111, 0.30864198, 0.60493827, 1.        ])

### Vector second member

In [16]:
Q_T_b = np.dot(Q.transpose(), Y)
Q_T_b

array([-1.28833534e+00,  1.66533454e-16,  1.13472842e+00, -1.11022302e-16,
        5.55111512e-17,  2.77555756e-17])

### Resolution

In [17]:
scipy.linalg.solve(R, Q_T_b)

array([ 1.60679286e-16, -1.12589077e-16,  1.00000000e+00,  4.15983009e-16,
       -1.77351976e-16, -1.83385716e-16])