## Numerical Linear Algebra
## Homework_1 Exercise_1

### Libraries importation

In [1]:
import numpy
import scipy . linalg

from scipy.sparse import diags
import numpy as np

### Tridiagonal Matrix

In [4]:
n = 3
k = [- np.ones(n-1), 2*np.ones(n), - np.ones(n-1)]
offset = [-1,0,1]
A = diags(k,offset).toarray()
A

array([[ 2., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  2.]])

### LU Factorization

In [5]:
LU = scipy.linalg.lu(A)
LU

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.5       ,  1.        ,  0.        ],
        [ 0.        , -0.66666667,  1.        ]]),
 array([[ 2.        , -1.        ,  0.        ],
        [ 0.        ,  1.5       , -1.        ],
        [ 0.        ,  0.        ,  1.33333333]]))

### Linear system resolution

In [20]:
def system_resolution(A, b):
    x = scipy.linalg.solve(A,b)
    return x

system_resolution(A, np.random.random(50))

array([ 14.69350922,  28.93167552,  42.68978242,  55.89769248,
        68.77179142,  81.59817865,  93.67164529, 105.11438905,
       115.67007488, 125.50214748, 135.06050428, 143.72842782,
       151.5441954 , 158.67793718, 165.269126  , 171.4860774 ,
       176.93202227, 181.72017909, 185.62965941, 189.40092928,
       192.75909032, 195.2336022 , 196.84632652, 197.52821332,
       197.57134423, 197.51219818, 197.28616836, 196.44085296,
       195.0987403 , 193.46159102, 190.92630733, 187.49267868,
       183.58435955, 179.43101065, 174.28213703, 168.2320035 ,
       161.40504123, 153.68813018, 145.25586847, 135.82442518,
       125.87767727, 115.43544039, 104.45857263,  93.20555795,
        81.16946144,  68.67723965,  55.90370005,  42.30721428,
        28.5441443 ,  14.68819501])